
CREATE DATABASE FirstDB 


SELECT * FROM  customer_behaviour_analysis

--Business Insights Questions

--1. Which category generates highest revenue?
SELECT category, ROUND(SUM(purchase_amount):: NUMERIC,2) AS highest_revenue FROM customer_behaviour_analysis
GROUP BY category
ORDER BY highest_revenue DESC


--2. Are discounts actually increasing purchase value?
SELECT discount_applied,ROUND(SUM(purchase_amount)::NUMERIC,2) AS purchase_value,
ROUND(AVG(purchase_amount)::NUMERIC,2) AS avg_purchase
 FROM customer_behaviour_analysis
GROUP BY discount_applied 
ORDER BY purchase_value DESC

--3. What is the total revenue generated by male and female customer ?
SELECT gender, ROUND(SUM(purchase_amount)::NUMERIC,2) AS revenue 
FROM customer_behaviour_analysis
GROUP BY gender
ORDER BY revenue DESC

--4. Which customer used a discount but still spent more then the average purchase amount?
SELECT customer_id,ROUND(purchase_amount::NUMERIC,2) AS purchase_amount FROM customer_behaviour_analysis
WHERE( discount_applied = 'Yes') 
AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_behaviour_analysis)
ORDER BY purchase_amount DESC
LIMIT 10;

--5. Which are the top/bottom 5 product with the higest average review rating ?
SELECT * FROM customer_behaviour_analysis

SELECT item_purchased, ROUND(AVG(review_rating)::NUMERIC,2) AS review_rating FROM customer_behaviour_analysis
GROUP BY item_purchased 
ORDER BY review_rating DESC
LIMIT 5;

SELECT item_purchased, ROUND(AVG(review_rating)::NUMERIC,2) AS review_rating FROM customer_behaviour_analysis
GROUP BY item_purchased 
ORDER BY review_rating ASC
LIMIT 5;

--6. Average purchase: Standard vs Express shipping
SELECT * FROM customer_behaviour_analysis
SELECT shipping_type,COUNT(DISTINCT customer_id) AS order_placed , ROUND(AVG(purchase_amount )::NUMERIC,2) AS avg_purchase FROM customer_behaviour_analysis
WHERE shipping_type IN ('Express','Standard') 
GROUP BY shipping_type;

--7. Do subscribed customers spend more ? Compare average spend and total revenue b/w subscribers & non-subscribers.

SELECT * FROM customer_behaviour_analysis

SELECT subscription_status,COUNT(DISTINCT customer_id) AS users,ROUND(AVG(purchase_amount)::NUMERIC,2) AS average_spend,
ROUND(SUM(purchase_amount)::NUMERIC,2 ) AS total_revenue
FROM customer_behaviour_analysis
GROUP BY subscription_status
ORDER BY total_revenue DESC;

--8. Top 5 products with highest discount usage %
SELECT * FROM customer_behaviour_analysis

SELECT item_purchased, COUNT(item_purchased) AS total_no_of_time_sold ,
COUNT(CASE WHEN discount_applied ='Yes' THEN 1 END) AS total_no_of_discount_applied,
ROUND(COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END )*100/COUNT(*)::NUMERIC,2) AS discount_percent
FROM customer_behaviour_analysis
GROUP BY item_purchased
ORDER BY discount_percent DESC
LIMIT 5;

--9. Segment customer into new, returning and loyal based on their total number of previous purchase, 
-- and show the count of each segment.
SELECT CASE WHEN previous_purchases = '0' THEN 'New Customer'
			WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
			ELSE 'Loyal Customer' END AS customer_segment,
			COUNT(*) AS customer_count
FROM customer_behaviour_analysis
GROUP BY customer_segment
ORDER BY customer_count DESC;

--10. What are the top 3 most purchased products within each category ?
SELECT * FROM customer_behaviour_analysis

WITH CTE AS
(SELECT category, item_purchased, COUNT(item_purchased) AS products ,
RANK() OVER(PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS rnk
FROM customer_behaviour_analysis
GROUP BY category,item_purchased)

SELECT * FROM CTE
WHERE rnk <=3

--11. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?
SELECT * FROM customer_behaviour_analysis

SELECT 
CASE WHEN previous_purchases >5 THEN 'Repeat Buyers'
	ELSE 'Normal Buyers' END AS customer,
subscription_status,
COUNT(*) AS buyers,
ROUND(COUNT(*) * 100/ SUM(COUNT(*)) OVER(PARTITION BY CASE WHEN previous_purchases >5 THEN 'Repeat Buyers'
	ELSE 'Normal Buyers' END ),2) AS percents
FROM customer_behaviour_analysis
GROUP BY customer,subscription_status
ORDER BY buyers DESC

--12. What is the revenue contribution of each age group? 
SELECT * FROM customer_behaviour_analysis

SELECT 
CASE WHEN age BETWEEN 0 AND 17 THEN '0-17'
	WHEN age BETWEEN 18 AND 25 THEN '18-25'
	WHEN age BETWEEN 26 AND 35 THEN '26-35'
	WHEN age BETWEEN 36 AND 50 THEN '36-50'
	ELSE '51+' END AS age_diff,
ROUND(SUM(purchase_amount)::NUMERIC,2)AS revenue  FROM customer_behaviour_analysis
GROUP BY age_diff
ORDER BY revenue DESC


